theme: jekyll-theme-hacker
title: Retro4Hack
description: Our Journey in the world of Cybersecurity and Programming
url: retrohacking.github.io
author:
  name: Retro
  email: retro4hack@gmail.com
  url: retrohacking.github.io
github:
  repository_url: https://github.com/retrohacking


paginate: 3
owner: Retro
year: 2022
excerpt_separator: <!--excerpt-->



url: "https://retrohacking.github.io" #
baseurl:
permalink: /:title/



